# Generated by Django 5.0.7 on 2024-09-01 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_employee_birthday_email_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='birthday_email_sent',
        ),
    ]
